In [4]:
import numpy as np

In [5]:
array_1d =np.array([1,2,3,4,5,6,7,8,9,10])

In [4]:
print(array_1d.max())
print(array_1d.min())
print(array_1d.sum())

10
1
55


查看维度信息

In [15]:
array_1d.shape

(10,)

In [16]:
array_1d.reshape(10)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
array_1d.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
np.average(array_2d)

5.0

切片

In [6]:
array_1d[2:7]

array([3, 4, 5, 6, 7])

In [7]:
array_1d[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
array_2d[1,2]  #第2行第3列

6

In [11]:
array_2d[:2,2]  #前2行的第三列的2个元素

array([3, 6])

In [12]:
array_2d[:2,:]  #前2行（全部列）的元素

array([[1, 2, 3],
       [4, 5, 6]])

广播

向量化计算

In [14]:
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])

In [15]:
C=np.dot(A,B)    #点积
print(A)
print(B)
print(C)

[[1 2 3]
 [4 5 6]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[[ 92  98 104 110]
 [218 233 248 263]]


In [16]:
D=np.exp(A)  #矩阵的每个元素都成为以e为底，指数为原元素

In [17]:
print(D)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
