In [1]:
import numpy as np

一维数组的axis

In [2]:
a=np.array([1,3,5,7]) # 构造个一维数组
np.max(a)

7

In [5]:
np.max(a,axis=0)

7

In [6]:
np.max(a,axis=1) #axis=1超出范围

AxisError: axis 1 is out of bounds for array of dimension 1

In [8]:
a=np.array([[0,1,2,3,4],[10,11,12,13,14],[20,21,22,23,24]]) # 构造个3x5二维数组
np.max(a) # 全体成员中的最大值

24

In [10]:
a.shape # 显示数组维数

(3, 5)

In [11]:
np.max(a,axis=0) # {第1列0轴上各元素的最大值，第2列0轴上各元素的最大值,...第5列0轴上各元素的最大值}

array([20, 21, 22, 23, 24])

In [12]:
np.max(a,axis=1) # {第1行1轴上各元素的最大值，第2行1轴上各元素的最大值,第3行1轴上各元素的最大值}

array([ 4, 14, 24])

三维数据

In [2]:
a=np.array([[[100,1,  2,  3,  4],  [10, 111,12, 13, 14], [20, 21, 22, 123,24]],
            [[0,  101,102,103,104],[110,11, 112,113,114],[120,121,122,23, 124]]]) # 构造个2x3x5三维数组
a.shape # 显示数组维数

(2, 3, 5)

In [3]:
np.max(a) # 全体成员中的最大值

124

In [4]:
np.max(a,axis=0) # 例如：第1个元素=max(第1页的第1行第1列的元素=100，第2页的第1行第1列的元素=0)

array([[100, 101, 102, 103, 104],
       [110, 111, 112, 113, 114],
       [120, 121, 122, 123, 124]])

In [5]:
np.max(a,axis=1) # 例如：第2个元素=max(第1页的第1行第2列的元素=1，第1页的第2行第2列的元素=111,第1页的第3行第2列的元素=21)

array([[100, 111,  22, 123,  24],
       [120, 121, 122, 113, 124]])

In [6]:
np.max(a,axis=2) # 例如：第3个元素=第1页的第3行的元素最大值=max(20,21,22,123,24)

array([[100, 111, 123],
       [104, 114, 124]])

四维数组

In [7]:
a=np.array([[[[100,1,2,3,2104],[10,111,12,3013,14],[3120,21,22,123,24]],     # 第1册第1页
        [[0,3101,102,103,104],[3010,11,112,113,114],[120,121,122,23,3114]]], # 第1册第2页
           [[[1000,1001,1002,1003,1004],[1010,1011,1012,1013,1014],[1020,1021,1022,1023,1024]], #第2册第1页
           [[1100,1101,1102,1103,1104],[1110,1111,1112,1113,1114],[1120,1121,1122,1123,1124]]], #第2册第2页
           [[[2000,2001,2002,2003,2004],[2010,2011,2012,2013,2014],[2020,2021,2022,2023,2024]], #第3册第1页
           [[2100,2101,2102,2103,4],[2110,2111,2112,2113,2114],[2120,2121,2122,2123,2124]]],    #第3册第2页
           [[[3000,3001,3002,3003,3004],[110,3011,3012,13,3014],[3020,3021,3022,3023,3024]],    #第4册第1页
           [[3100,101,3102,3103,3104],[3110,3111,3112,3113,124],[20,3121,3122,3123,3124]]]])    #第4册第2页
a.shape # 显示数组维数

(4, 2, 3, 5)

In [8]:
np.max(a,axis=0) # 新集合2页x3行x5列

array([[[3000, 3001, 3002, 3003, 3004],
        [2010, 3011, 3012, 3013, 3014],
        [3120, 3021, 3022, 3023, 3024]],

       [[3100, 3101, 3102, 3103, 3104],
        [3110, 3111, 3112, 3113, 2114],
        [2120, 3121, 3122, 3123, 3124]]])

In [9]:
np.max(a,axis=1) # 新集合4册x3行x5列

array([[[ 100, 3101,  102,  103, 2104],
        [3010,  111,  112, 3013,  114],
        [3120,  121,  122,  123, 3114]],

       [[1100, 1101, 1102, 1103, 1104],
        [1110, 1111, 1112, 1113, 1114],
        [1120, 1121, 1122, 1123, 1124]],

       [[2100, 2101, 2102, 2103, 2004],
        [2110, 2111, 2112, 2113, 2114],
        [2120, 2121, 2122, 2123, 2124]],

       [[3100, 3001, 3102, 3103, 3104],
        [3110, 3111, 3112, 3113, 3014],
        [3020, 3121, 3122, 3123, 3124]]])

In [10]:
np.max(a,axis=2) # 新集合4册x2页x5列

array([[[3120,  111,   22, 3013, 2104],
        [3010, 3101,  122,  113, 3114]],

       [[1020, 1021, 1022, 1023, 1024],
        [1120, 1121, 1122, 1123, 1124]],

       [[2020, 2021, 2022, 2023, 2024],
        [2120, 2121, 2122, 2123, 2124]],

       [[3020, 3021, 3022, 3023, 3024],
        [3110, 3121, 3122, 3123, 3124]]])

In [11]:
np.max(a,axis=3) # 新集合4册x2页x3行

array([[[2104, 3013, 3120],
        [3101, 3010, 3114]],

       [[1004, 1014, 1024],
        [1104, 1114, 1124]],

       [[2004, 2014, 2024],
        [2103, 2114, 2124]],

       [[3004, 3014, 3024],
        [3104, 3113, 3124]]])

In [12]:
np.max(a) # 全部元素的最大值

3124