张量操作

In [1]:
import paddle.fluid as fluid

In [2]:
data = fluid.layers.ones(shape=[5],dtype='int64')   #定义数组
place = fluid.CPUPlace()          #在CPU上运算
exe = fluid.Executor(place)       #创建执行器
ones_result = exe.run(fluid.default_main_program(),
                     fetch_list=[data], #默认的元素=1
                     return_numpy=True)

In [3]:
print(ones_result[0])

[1 1 1 1 1]


In [4]:
ones_result

[array([1, 1, 1, 1, 1], dtype=int64)]

In [5]:
#两个数组按位相加
add = fluid.layers.elementwise_add(data,data)
place = fluid.CPUPlace()          #在CPU上运算
exe = fluid.Executor(place)       #创建执行器
add_result = exe.run(fluid.default_main_program(),
                     fetch_list=[add],  
                     return_numpy=True)

In [7]:
print(add_result[0])

[2 2 2 2 2]


In [8]:
#转换数组的数据类型
cast= fluid.layers.cast(x=data,dtype='float64')
place = fluid.CPUPlace()          #在CPU上运算
exe = fluid.Executor(place)       #创建执行器
cast_result = exe.run(fluid.default_main_program(),
                     fetch_list=[cast],  
                     return_numpy=True)

In [9]:
print(cast_result[0])

[1. 1. 1. 1. 1.]


In [11]:
cast_result

[array([1., 1., 1., 1., 1.])]