In [11]:
L1=['1','2','3']
lt2=['4',5,6]
lt3=zip(L1,lt2)

In [12]:
print(list(lt3))

[('1', '4'), ('2', 5), ('3', 6)]


In [13]:
print(dict(lt3))

{}


In [14]:
a=1*[0]

In [15]:
a

[0]

In [16]:
import numpy as np

In [17]:
a=np.array([[0,1,2,3],[10,11,12,13],[20,21,22,23]])

In [18]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23]])

In [19]:
b=a[0]

In [20]:
b

array([0, 1, 2, 3])

In [21]:
b=a[1][0]

In [22]:
b

10

In [23]:
b=a[0]+a[1][0]
b

array([10, 11, 12, 13])

In [24]:
b=a[0]+a[1]
b

array([10, 12, 14, 16])

In [26]:
a=[x*x for x in range(1,11) if x%2==0]
a

[4, 16, 36, 64, 100]

In [27]:
%matplotlib inline